services:
  # Backend service
  - type: web
    name: document-research-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: QDRANT_URL
        sync: false

  # Frontend service
  - type: web
    name: document-research-frontend
    env: python
    buildCommand: |
      cd frontend
      pip install -r requirements.txt
    startCommand: |
      cd frontend
      streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: BACKEND_URL
        value: https://document-research-backend.onrender.com 